# Generated by Django 4.1.5 on 2023-01-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='replenishment',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount_money', models.PositiveIntegerField()),
            ],
        ),
    ]
