# Generated by Django 4.1.5 on 2023-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replenishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishment',
            name='user_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
